# Multi-stage production build for Sona
FROM node:20-alpine AS builder

WORKDIR /app

# Declare build arguments so Railway injects dashboard variables into the Vite build
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID

ARG VITE_FINNHUB_API_KEY
ARG VITE_GROQ_API_KEY
ARG VITE_SONA_API_URL

ARG VITE_SOLANA_NETWORK
ARG VITE_SOLANA_RPC_URL

ARG VITE_TRADING_PROGRAM_ID_MAINNET
ARG VITE_TRADING_PROGRAM_ID_DEVNET
ARG VITE_TRADING_PROGRAM_ID_TESTNET
ARG VITE_TRANSFER_PROGRAM_ID_MAINNET
ARG VITE_TRANSFER_PROGRAM_ID_DEVNET
ARG VITE_TRANSFER_PROGRAM_ID_TESTNET

ARG VITE_PLATFORM_FEE_RECIPIENT
ARG VITE_BACKEND_URL
ARG VITE_DEMO_MODE

# Pass build arguments to Vite bundling environment
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID \
    VITE_FINNHUB_API_KEY=$VITE_FINNHUB_API_KEY \
    VITE_GROQ_API_KEY=$VITE_GROQ_API_KEY \
    VITE_SONA_API_URL=$VITE_SONA_API_URL \
    VITE_SOLANA_NETWORK=$VITE_SOLANA_NETWORK \
    VITE_SOLANA_RPC_URL=$VITE_SOLANA_RPC_URL \
    VITE_TRADING_PROGRAM_ID_MAINNET=$VITE_TRADING_PROGRAM_ID_MAINNET \
    VITE_TRADING_PROGRAM_ID_DEVNET=$VITE_TRADING_PROGRAM_ID_DEVNET \
    VITE_TRADING_PROGRAM_ID_TESTNET=$VITE_TRADING_PROGRAM_ID_TESTNET \
    VITE_TRANSFER_PROGRAM_ID_MAINNET=$VITE_TRANSFER_PROGRAM_ID_MAINNET \
    VITE_TRANSFER_PROGRAM_ID_DEVNET=$VITE_TRANSFER_PROGRAM_ID_DEVNET \
    VITE_TRANSFER_PROGRAM_ID_TESTNET=$VITE_TRANSFER_PROGRAM_ID_TESTNET \
    VITE_PLATFORM_FEE_RECIPIENT=$VITE_PLATFORM_FEE_RECIPIENT \
    VITE_BACKEND_URL=$VITE_BACKEND_URL \
    VITE_DEMO_MODE=$VITE_DEMO_MODE

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source code
COPY . .

# Build Vite production bundle with environment variables baked in
RUN npm run build

# Production runner stage
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

# Install lightweight static file server with SPA routing support
RUN npm install -g serve

# Copy built frontend assets
COPY --from=builder /app/dist ./dist

# Railway default port
EXPOSE 8080
EXPOSE 3000

# Start static server binding to 0.0.0.0 and dynamic $PORT with SPA fallback (-s)
CMD ["sh", "-c", "serve -s dist -l tcp://0.0.0.0:${PORT:-8080}"]
